/**
 * NARASI - Policy Insight Card.
 * Evidence-based trade-off summary generated by the rule engine. Never issues
 * unsupported authoritative recommendations (EXECUTION RULES §6).
 */

import { AlertTriangle, CheckCircle2, Info, MinusCircle, TrendingDown } from 'lucide-react';
import type { PolicyInsight, Verdict } from '../../types/simulation';

const VERDICT_STYLE: Record<Verdict, { color: string; label: string; icon: React.ReactNode }> = {
  HIGHLY_EFFECTIVE: {
    color: 'text-brand-emerald border-brand-emerald/50 bg-brand-emerald/10',
    label: 'HIGHLY EFFECTIVE',
    icon: <CheckCircle2 size={12} />,
  },
  TRADE_OFF_HEAVY: {
    color: 'text-brand-amber border-brand-amber/50 bg-brand-amber/10',
    label: 'TRADE-OFF HEAVY',
    icon: <AlertTriangle size={12} />,
  },
  COST_INEFFECTIVE: {
    color: 'text-brand-crimson border-brand-crimson/50 bg-brand-crimson/10',
    label: 'COST INEFFECTIVE',
    icon: <TrendingDown size={12} />,
  },
  NEUTRAL: {
    color: 'text-slate-400 border-slate-500/50 bg-slate-500/10',
    label: 'NEUTRAL',
    icon: <MinusCircle size={12} />,
  },
};

export function PolicyInsightCard({ insight }: { insight: PolicyInsight }) {
  const verdict = VERDICT_STYLE[insight.verdict];

  return (
    <div className="glass-card flex h-full flex-col gap-2 p-4">
      <div className="flex items-center justify-between gap-2">
        <h3 className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-widest text-slate-400">
          <Info size={12} className="text-brand-cyan" />
          Policy Insight
        </h3>
        <span
          className={`flex items-center gap-1 rounded border px-2 py-0.5 font-mono text-[9px] font-bold ${verdict.color}`}
        >
          {verdict.icon}
          {verdict.label}
        </span>
      </div>

      <p className="text-sm font-semibold leading-snug text-white">{insight.headline}</p>

      <ul className="space-y-1">
        {insight.keyTakeaways.map((t, i) => (
          <li key={i} className="flex gap-1.5 text-[11px] leading-snug text-slate-300">
            <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-brand-cyan" />
            {t}
          </li>
        ))}
      </ul>

      <div className="mt-auto rounded-md border border-edge/70 bg-panel/60 p-2.5">
        <p className="text-[11px] leading-snug text-slate-300">
          <span className="font-bold text-slate-200">Consideration: </span>
          {insight.recommendation}
        </p>
      </div>

      <p className="font-mono text-[9px] uppercase tracking-wider text-slate-600">
        [SIMULATED EXPERIMENT OUTPUT]
      </p>
    </div>
  );
}
